import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // ===== COMMON =====
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    refresh: "Refresh",
    close: "Close",
    actions: "Actions",
    status: "Status",
    yes: "Yes",
    no: "No",
    all: "All",
    back: "Back",
    confirm: "Confirm",
    warning: "Warning",
    error: "Error",
    success: "Success",
    noData: "No data found.",
    details: "Details",

    // ===== LOGIN =====
    loginTitle: "Hotel PMS",
    loginSubtitle: "Sign in to your account",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidCredentials: "Invalid credentials",
    loginFooter: "Hotel Property Management System",

    // ===== LAYOUT =====
    dashboard: "Dashboard",
    roomBoard: "Room Board",
    rooms: "Rooms",
    reservations: "Reservations",
    vouchers: "Vouchers",
    payments: "Payments",
    housekeeping: "Housekeeping",
    reports: "Reports",
    backups: "Backups",
    auditLogs: "Audit Logs",
    users: "Users",
    settings: "Settings",
    logout: "Logout",
    hotelManagement: "Hotel Management",

    // ===== DASHBOARD =====
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Welcome back! Here is what's happening at your hotel today.",
    todayRevenue: "Today Revenue",
    monthlyRevenue: "Monthly Revenue",
    arrivalsToday: "Arrivals Today",
    departuresToday: "Departures Today",
    occupancyRate: "Occupancy Rate",
    roomStatusOverview: "Room Status Overview",
    available: "Available",
    occupied: "Occupied",
    reserved: "Reserved",
    cleaning: "Cleaning",
    maintenance: "Maintenance",
    blocked: "Blocked",
    quickActions: "Quick Actions",
    newReservation: "New Reservation",
    viewRoomBoard: "View Room Board",
    recordPayment: "Record Payment",
    todayArrivals: "Today Arrivals",
    todayDepartures: "Today Departures",
    recentPayments: "Recent Payments",
    needsAttention: "Needs Attention",
    noArrivals: "No arrivals today",
    noDepartures: "No departures today",
    noRecentPayments: "No recent payments",
    allRoomsOkay: "All rooms are okay",
    guests: "guests",
    of: "of",
    roomsText: "rooms",

    // ===== ROOMS =====
    roomsTitle: "Rooms Management",
    roomsSubtitle: "Manage your hotel rooms, pricing, and capacity.",
    addNewRoom: "Add New Room",
    roomSearchPlaceholder: "Search by room number or type...",
    room: "Room",
    type: "Type",
    capacity: "Capacity",
    floor: "Floor",
    pricePerNight: "Price / Night",
    editRoom: "Edit Room",
    roomNumber: "Room Number",
    roomType: "Room Type",
    maxGuests: "Max Guests (Capacity)",
    basePrice: "Base Price",
    extraBedPrice: "Extra Bed Price",
    overtimeRate: "Overtime Rate (Hr)",
    createRoom: "Create Room",
    saveChanges: "Save Changes",
    roomCreated: "Room created successfully",
    roomUpdated: "Room updated successfully",
    roomDisabled: "Room disabled",
    disableRoomConfirm: "Are you sure you want to disable this room?",
    singleRoom: "1 Person (Single)",
    doubleRoom: "2 Persons (Double)",
    threePerson: "3 Persons",
    familyRoom: "4 Persons (Family)",
    fivePerson: "5 Persons",
    largeFamily: "6 Persons (Large Family)",
    groupRoom8: "8 Persons (Group)",
    groupRoom10: "10 Persons (Group)",
    standardRoom: "Standard",
    superiorRoom: "Superior",
    deluxeRoom: "Deluxe",
    premiumRoom: "Premium",
    executiveRoom: "Executive",
    familyRoomType: "Family Room",

    // ===== ROOM BOARD =====
    roomBoardTitle: "Room Board",
    roomBoardSubtitle: "Visual overview of all room statuses by floor.",
    reserve: "Reserve",
    walkIn: "Walk-In",
    walkInShort: "Walk-In",
    pax: "PAX",
    night: "night",

    // ===== RESERVATIONS =====
    reservationsTitle: "Reservations",
    reservationsSubtitle: "Manage bookings, walk-ins, check-in, and check-out.",
    booking: "Booking",
    guest: "Guest",
    idLabel: "ID",
    checkIn: "Check In",
    checkOut: "Check Out",
    total: "Total",
    reservationSearchPlaceholder: "Search booking, guest, room, NRC, passport...",
    guestName: "Guest Name",
    guestPhone: "Guest Phone",
    guestType: "Guest Type",
    local: "Local (NRC)",
    foreigner: "Foreigner (Passport)",
    nrc: "NRC Number",
    passport: "Passport Number",
    nrcPlaceholder: "e.g. 12/YGN(N)123456",
    passportPlaceholder: "e.g. MA123456",
    adults: "Adults",
    children: "Children",
    extraBeds: "Extra Beds",
    voucherCode: "Voucher Code",
    enterCode: "Enter code",
    createReservationBtn: "Create Reservation",
    checkInWalkInGuest: "Check In Walk-In Guest",
    walkInMode: "Walk-in mode: Guest will be checked in immediately after creation.",
    walkInCheckInNote: "Walk-in: check-in is set to now",
    capacityLabel: "Capacity",
    guestsMax: "guests max",
    capacityWarning: "Warning: Total guests exceeds room capacity. You can still proceed.",
    reservationCreated: "Reservation created successfully",
    walkInSuccess: "Walk-in guest checked in successfully",
    checkedIn: "Checked in",
    checkedOut: "Checked out",
    reservationCancelled: "Cancelled",
    walkInBadge: "WALK-IN",

    // ===== VOUCHERS =====
    vouchersTitle: "Vouchers",
    vouchersSubtitle: "Manage discount codes.",
    newVoucher: "New Voucher",
    code: "Code",
    usage: "Usage",
    validTo: "Valid To",
    active: "Active",
    disabled: "Disabled",
    fixedAmount: "Fixed Amount",
    percentage: "Percentage",
    value: "Value",
    maxDiscount: "Max Discount",
    usageLimit: "Usage Limit",
    validFrom: "Valid From",
    createVoucherBtn: "Create Voucher",
    voucherCreated: "Voucher created",
    voucherDisabled: "Voucher disabled",
    voucherSearchPlaceholder: "Search by code...",

    // ===== PAYMENTS =====
    paymentsTitle: "Payments",
    paymentsSubtitle: "Record payments and view balances.",
    balances: "Balances",
    paymentHistory: "Payment History",
    paid: "Paid",
    balance: "Balance",
    receipt: "Receipt",
    method: "Method",
    amount: "Amount",
    date: "Date",
    reference: "Reference",
    note: "Note",
    savePaymentBtn: "Save Payment",
    cash: "Cash",
    card: "Card",
    bankTransfer: "Bank Transfer",
    other: "Other",
    paymentRecorded: "Payment recorded",
    paymentSearchPlaceholder: "Search...",
    paidInFull: "Paid",

    // ===== INVOICE =====
    hotelInvoice: "Hotel Invoice",
    invoiceDate: "Invoice Date",
    bookingNo: "Booking No",
    phone: "Phone",
    charges: "Charges",
    roomCharge: "Room Charge",
    extraBed: "Extra Bed",
    overtime: "Overtime",
    voucherDiscount: "Voucher Discount",
    totalLabel: "Total",
    paymentsLabel: "Payments",
    summary: "Summary",
    paidLabel: "Paid",
    balanceLabel: "Balance",
    paidInFullLabel: "PAID IN FULL",
    balanceDue: "BALANCE DUE",
    print: "Print",
    backToPayments: "Back to Payments",

    // ===== HOUSEKEEPING =====
    housekeepingTitle: "Housekeeping",
    housekeepingSubtitle: "Manage cleaning and maintenance tasks.",
    newTask: "New Task",
    priority: "Priority",
    assigned: "Assigned",
    created: "Created",
    cleaningType: "Cleaning",
    maintenanceType: "Maintenance",
    inspection: "Inspection",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    notes: "Notes",
    createTaskBtn: "Create Task",
    taskCreated: "Task created",
    taskCompleted: "Task completed",
    unassigned: "Unassigned",
    assignTo: "Assign To",
    selectRoom: "Select room",

    // ===== USERS =====
    usersTitle: "User Management",
    usersSubtitle: "Manage system users and roles.",
    addUser: "Add User",
    user: "User",
    role: "Role",
    name: "Name",
    editUser: "Edit User",
    createUserBtn: "Create User",
    resetPassword: "Reset Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    updatePassword: "Update Password",
    userCreated: "User created",
    userUpdated: "User updated",
    userDisabled: "User disabled",
    userEnabled: "User enabled",
    passwordUpdated: "Password updated",
    userSearchPlaceholder: "Search users...",
    minSixChars: "Min 6 characters",
    admin: "Admin",
    manager: "Manager",
    reception: "Reception",
    cleaner: "Cleaner",

    // ===== SETTINGS =====
    settingsTitle: "Settings",
    settingsSubtitle: "Configure hotel information, currency, timezone, and backup.",
    hotelInfo: "Hotel Information",
    hotelName: "Hotel Name",
    contactEmail: "Contact Email",
    contactPhone: "Contact Phone",
    address: "Address",
    regionalSettings: "Regional Settings",
    language: "Language",
    currency: "Currency",
    currencySymbol: "Currency Symbol",
    timezone: "Timezone",
    operations: "Operations",
    checkInTime: "Check-In Time",
    checkOutTime: "Check-Out Time",
    taxRate: "Tax Rate %",
    overtimeGrace: "Overtime Grace (min)",
    invoiceFooter: "Invoice Footer",
    saveSettings: "Save Settings",
    saving: "Saving...",
    settingsSaved: "Settings saved successfully",
    english: "English",
    myanmar: "Myanmar",
    autoBrowser: "Auto (Browser)",

    // ===== REPORTS =====
    reportsTitle: "Reports & Analytics",
    reportsSubtitle: "Comprehensive hotel reports with guest details, revenue, and payments.",
    overview: "Overview",
    guestList: "Guest List",
    paymentsTab: "Payments",
    revenue: "Revenue",
    unpaid: "Unpaid",
    from: "From",
    to: "To",
    apply: "Apply",
    today: "Today",
    thisMonth: "This Month",
    totalRevenueLabel: "Total Revenue",
    totalPayments: "Total Payments",
    reservationsLabel: "Reservations",
    occupancy: "Occupancy",
    arrivals: "Arrivals",
    departures: "Departures",
    cancellations: "Cancellations",
    totalUnpaid: "Total Unpaid",
    revenueByDate: "Revenue By Date",
    paymentsByMethod: "Payments By Method",
    exportCsv: "CSV",
    exportAllGuests: "Export All Guests",
    exportPayments: "Export Payments",
    exportUnpaid: "Export Unpaid",
    guestSearchPlaceholder: "Search by name, booking, NRC, passport, room...",
    paymentMethods: "Payment Methods",
    transactions: "Transactions",
    additionalInfo: "Additional Info",
    noPayments: "No payments",
    noTransactions: "No transactions",
    booked: "Booked",
    totalAmount: "Total Amount",
    totalTransactions: "Total Transactions",
    outstandingBalance: "Total Outstanding Balance",
    allClear: "No unpaid reservations. All clear!",
    receiptNo: "Receipt No",

    // ===== BACKUPS =====
    backupsTitle: "Backup & Restore",
    backupsSubtitle: "Create, download, and restore database backups.",
    createBackupBtn: "Create Backup",
    creating: "Creating...",
    restoreFromFile: "Restore From File",
    restoreWarning: "Warning: this will overwrite all current data.",
    iUnderstand: "I understand",
    restoreBtn: "Restore",
    restoring: "Restoring...",
    filename: "Filename",
    size: "Size",
    download: "Download",
    backupCreated: "Backup created",
    backupDeleted: "Deleted",
    restoreCompleted: "Restore completed",
    chooseFile: "Choose a file",
    pleaseConfirm: "Please confirm",
    overwriteConfirm: "This will overwrite all current data. Are you sure?",

    // ===== AUDIT LOGS =====
    auditTitle: "Audit Logs",
    auditSubtitle: "Track all system activities and data changes.",
    time: "Time",
    entity: "Entity",
    ip: "IP",
    before: "Before",
    after: "After",
    device: "Device",
    auditSearch: "Search",
    allUsers: "All",
    allEntities: "All",
    noActivities: "No activities found.",
  },

  my: {
    // ===== COMMON =====
    loading: "ဖတ်နေသည်...",
    save: "သိမ်းရန်",
    cancel: "ပယ်ဖျက်ရန်",
    create: "ဖန်တီးရန်",
    edit: "ပြင်ဆင်ရန်",
    delete: "ဖျက်ရန်",
    search: "ရှာဖွေရန်",
    refresh: "အသစ်ပြန်လုပ်ရန်",
    close: "ပိတ်ရန်",
    actions: "လုပ်ဆောင်ချက်များ",
    status: "အခြေအနေ",
    yes: "ဟုတ်ကဲ့",
    no: "မဟုတ်ပါ",
    all: "အားလုံး",
    back: "နောက်သို့",
    confirm: "အတည်ပြုရန်",
    warning: "သတိပေးချက်",
    error: "အမှား",
    success: "အောင်မြင်ပါသည်",
    noData: "ဒေတာ မတွေ့ပါ။",
    details: "အသေးစိတ်",

    // ===== LOGIN =====
    loginTitle: "ဟိုတယ် စနစ်",
    loginSubtitle: "သင့်အကောင့်သို့ ဝင်ရောက်ပါ",
    username: "အသုံးပြုသူနာမည်",
    password: "စကားဝှက်",
    signIn: "ဝင်ရောက်ရန်",
    signingIn: "ဝင်ရောက်နေသည်...",
    invalidCredentials: "အသုံးပြုသူနာမည် သို့မဟုတ် စကားဝှက် မှားနေပါသည်",
    loginFooter: "ဟိုတယ် စီမံခန့်ခွဲမှု စနစ်",

    // ===== LAYOUT =====
    dashboard: "ဒက်ရှ်ဘုတ်",
    roomBoard: "အခန်းဘုတ်",
    rooms: "အခန်းများ",
    reservations: "ကြိုတင်ဘွတ်များ",
    vouchers: "ဘောက်ချာများ",
    payments: "ငွေပေးချေမှုများ",
    housekeeping: "သန့်ရှင်းရေး",
    reports: "အစီရင်ခံစာများ",
    backups: "အရန်သိမ်းမှုများ",
    auditLogs: "စစ်ဆေးမှုမှတ်တမ်းများ",
    users: "အသုံးပြုသူများ",
    settings: "ဆက်တင်များ",
    logout: "ထွက်ရန်",
    hotelManagement: "ဟိုတယ် စီမံခန့်ခွဲမှု",

    // ===== DASHBOARD =====
    dashboardTitle: "ဒက်ရှ်ဘုတ်",
    dashboardSubtitle: "ကြိုဆိုပါသည်! ယနေ့ သင့်ဟိုတယ်၏ အခြေအနေကို ကြည့်ပါ။",
    todayRevenue: "ယနေ့ ဝင်ငွေ",
    monthlyRevenue: "လစဉ် ဝင်ငွေ",
    arrivalsToday: "ယနေ့ ဧည့်သည်ဝင်",
    departuresToday: "ယနေ့ ဧည့်သည်ထွက်",
    occupancyRate: "အခန်းပြည့်နှုန်း",
    roomStatusOverview: "အခန်းအခြေအနေ အနှစ်ချုပ်",
    available: "လွတ်နေသည်",
    occupied: "အသုံးပြုနေသည်",
    reserved: "ကြိုတင်ဘွတ်",
    cleaning: "သန့်ရှင်းရေး",
    maintenance: "ပြုပြင်ရေး",
    blocked: "ပိတ်ထားသည်",
    quickActions: "အမြန်လုပ်ဆောင်ချက်များ",
    newReservation: "ကြိုတင်ဘွတ် အသစ်",
    viewRoomBoard: "အခန်းဘုတ် ကြည့်ရန်",
    recordPayment: "ငွေပေးချေရန်",
    todayArrivals: "ယနေ့ ဧည့်သည်ဝင်",
    todayDepartures: "ယနေ့ ဧည့်သည်ထွက်",
    recentPayments: "လတ်တလော ငွေပေးချေမှုများ",
    needsAttention: "ဂရုပြုရန်",
    noArrivals: "ယနေ့ ဧည့်သည်ဝင် မရှိပါ",
    noDepartures: "ယနေ့ ဧည့်သည်ထွက် မရှိပါ",
    noRecentPayments: "လတ်တလော ငွေပေးချေမှု မရှိပါ",
    allRoomsOkay: "အခန်းအားလုံး ကောင်းပါသည်",
    guests: "ဧည့်သည်",
    of: "/",
    roomsText: "အခန်း",

    // ===== ROOMS =====
    roomsTitle: "အခန်း စီမံခန့်ခွဲမှု",
    roomsSubtitle: "ဟိုတယ်အခန်းများ၊ စျေးနှုန်းနှင့် ဧည့်သည် 수용နိုင်မှုကို စီမံပါ။",
    addNewRoom: "အခန်းအသစ် ထည့်ရန်",
    roomSearchPlaceholder: "အခန်းနံပါတ် သို့မဟုတ် အမျိုးအစားဖြင့် ရှာပါ...",
    room: "အခန်း",
    type: "အမျိုးအစား",
    capacity: "ဧည့်သည်수용နိုင်မှု",
    floor: "ထပ်",
    pricePerNight: "တစ်ည စျေးနှုန်း",
    editRoom: "အခန်း ပြင်ဆင်ရန်",
    roomNumber: "အခန်းနံပါတ်",
    roomType: "အခန်း အမျိုးအစား",
    maxGuests: "အများဆုံး ဧည့်သည် (ဧည့်သည်수용နိုင်မှု)",
    basePrice: "အခြေခံ စျေးနှုန်း",
    extraBedPrice: "အပိုကုတင် စျေးနှုန်း",
    overtimeRate: "အချိန်ပို စျေးနှုန်း (နာရီ)",
    createRoom: "အခန်း ဖန်တီးရန်",
    saveChanges: "ပြောင်းလဲမှုများ သိမ်းရန်",
    roomCreated: "အခန်း ဖန်တီးပြီးပါပြီ",
    roomUpdated: "အခန်း ပြင်ဆင်ပြီးပါပြီ",
    roomDisabled: "အခန်း ပိတ်ပြီးပါပြီ",
    disableRoomConfirm: "ဤအခန်းကို ပိတ်မှာ သေချာပါသလား?",
    singleRoom: "၁ ယောက် (တစ်ကိုယ်တော်)",
    doubleRoom: "၂ ယောက် (နှစ်ယောက်တွဲ)",
    threePerson: "၃ ယောက်",
    familyRoom: "၄ ယောက် (မိသားစု)",
    fivePerson: "၅ ယောက်",
    largeFamily: "၆ ယောက် (မိသားစုကြီး)",
    groupRoom8: "၈ ယောက် (အုပ်စု)",
    groupRoom10: "၁၀ ယောက် (အုပ်စု)",
    standardRoom: "Standard",
    superiorRoom: "Superior",
    deluxeRoom: "Deluxe",
    premiumRoom: "Premium",
    executiveRoom: "Executive",
    familyRoomType: "Family Room",

    // ===== ROOM BOARD =====
    roomBoardTitle: "အခန်းဘုတ်",
    roomBoardSubtitle: "ထပ်အလိုက် အခန်းအခြေအနေများကို ကြည့်ပါ။",
    reserve: "ဘွတ်ယူရန်",
    walkIn: "Walk-In",
    walkInShort: "Walk-In",
    pax: "ဧည့်သည်",
    night: "တစ်ည",

    // ===== RESERVATIONS =====
    reservationsTitle: "ကြိုတင်ဘွတ်များ",
    reservationsSubtitle: "ဘွတ်များ၊ Walk-in၊ Check-in နှင့် Check-out ကို စီမံပါ။",
    booking: "ဘွတ်နံပါတ်",
    guest: "ဧည့်သည်",
    idLabel: "မှတ်ပုံတင်",
    checkIn: "Check In",
    checkOut: "Check Out",
    total: "စုစုပေါင်း",
    reservationSearchPlaceholder: "ဘွတ်၊ ဧည့်သည်၊ အခန်း၊ NRC၊ ပတ်စပို့ ရှာပါ...",
    guestName: "ဧည့်သည် အမည်",
    guestPhone: "ဧည့်သည် ဖုန်း",
    guestType: "ဧည့်သည် အမျိုးအစား",
    local: "ပြည်တွင်း (မှတ်ပုံတင်)",
    foreigner: "နိုင်ငံခြားသား (ပတ်စပို့)",
    nrc: "မှတ်ပုံတင် နံပါတ်",
    passport: "ပတ်စပို့ နံပါတ်",
    nrcPlaceholder: "ဥပမာ 12/ရကန(န)123456",
    passportPlaceholder: "ဥပမာ MA123456",
    adults: "လူကြီး",
    children: "ကလေး",
    extraBeds: "အပိုကုတင်",
    voucherCode: "ဘောက်ချာ ကုဒ်",
    enterCode: "ကုဒ် ထည့်ပါ",
    createReservationBtn: "ဘွတ် ဖန်တီးရန်",
    checkInWalkInGuest: "Walk-In ဧည့်သည် Check In",
    walkInMode: "Walk-In: ဧည့်သည်သည် ဖန်တီးပြီးသည်နှင့် ချက်ချင်း Check In ဖြစ်ပါမည်။",
    walkInCheckInNote: "Walk-In: Check In သည် ယခုအချိန်ဖြစ်ပါသည်",
    capacityLabel: "ဧည့်သည်수용နိုင်မှု",
    guestsMax: "ဧည့်သည် အများဆုံး",
    capacityWarning: "သတိ: စုစုပေါင်း ဧည့်သည်သည် အခန်း수용နိုင်မှုထက် ကျော်လွန်နေပါသည်။ ဆက်လက်လုပ်ဆောင်နိုင်ပါသည်။",
    reservationCreated: "ဘွတ် ဖန်တီးပြီးပါပြီ",
    walkInSuccess: "Walk-In ဧည့်သည် Check In ပြီးပါပြီ",
    checkedIn: "Check In ပြီးပါပြီ",
    checkedOut: "Check Out ပြီးပါပြီ",
    reservationCancelled: "ပယ်ဖျက်ပြီးပါပြီ",
    walkInBadge: "WALK-IN",

    // ===== VOUCHERS =====
    vouchersTitle: "ဘောက်ချာများ",
    vouchersSubtitle: "လျှော့စျေး ကုဒ်များကို စီမံပါ။",
    newVoucher: "ဘောက်ချာ အသစ်",
    code: "ကုဒ်",
    usage: "အသုံးပြုမှု",
    validTo: "သက်တမ်းကုန်",
    active: "အသက်ဝင်",
    disabled: "ပိတ်ထား",
    fixedAmount: "ငွေပမာဏ အတိအကျ",
    percentage: "ရာခိုင်နှုန်း",
    value: "တန်ဖိုး",
    maxDiscount: "အများဆုံး လျှော့စျေး",
    usageLimit: "အသုံးပြုနိုင်သည့် အကြိမ်ရေ",
    validFrom: "စတင်ရက်",
    createVoucherBtn: "ဘောက်ချာ ဖန်တီးရန်",
    voucherCreated: "ဘောက်ချာ ဖန်တီးပြီးပါပြီ",
    voucherDisabled: "ဘောက်ချာ ပိတ်ပြီးပါပြီ",
    voucherSearchPlaceholder: "ကုဒ်ဖြင့် ရှာပါ...",

    // ===== PAYMENTS =====
    paymentsTitle: "ငွေပေးချေမှုများ",
    paymentsSubtitle: "ငွေပေးချေမှုများ မှတ်တမ်းတင်ပြီး လက်ကျန်ကြည့်ပါ။",
    balances: "လက်ကျန်များ",
    paymentHistory: "ငွေပေးချေမှု မှတ်တမ်း",
    paid: "ပေးချေပြီး",
    balance: "လက်ကျန်",
    receipt: "ဘောင်ချာ",
    method: "နည်းလမ်း",
    amount: "ပမာဏ",
    date: "ရက်စွဲ",
    reference: "ရည်ညွှန်း",
    note: "မှတ်ချက်",
    savePaymentBtn: "ငွေပေးချေမှု သိမ်းရန်",
    cash: "ငွေသား",
    card: "ကတ်",
    bankTransfer: "ဘဏ်လွှဲ",
    other: "အခြား",
    paymentRecorded: "ငွေပေးချေမှု မှတ်တမ်းတင်ပြီးပါပြီ",
    paymentSearchPlaceholder: "ရှာပါ...",
    paidInFull: "ပေးချေပြီး",

    // ===== INVOICE =====
    hotelInvoice: "ဟိုတယ် ဘောင်ချာ",
    invoiceDate: "ဘောင်ချာ ရက်စွဲ",
    bookingNo: "ဘွတ်နံပါတ်",
    phone: "ဖုန်း",
    charges: "ကျသင့်ငွေများ",
    roomCharge: "အခန်းခ",
    extraBed: "အပိုကုတင်",
    overtime: "အချိန်ပို",
    voucherDiscount: "ဘောက်ချာ လျှော့စျေး",
    totalLabel: "စုစုပေါင်း",
    paymentsLabel: "ငွေပေးချေမှုများ",
    summary: "အနှစ်ချုပ်",
    paidLabel: "ပေးချေပြီး",
    balanceLabel: "လက်ကျန်",
    paidInFullLabel: "အပြည့် ပေးချေပြီးပါပြီ",
    balanceDue: "လက်ကျန် ကျန်ရှိပါသည်",
    print: "ပရင့်ထုတ်ရန်",
    backToPayments: "ငွေပေးချေမှုများသို့ ပြန်သွားရန်",

    // ===== HOUSEKEEPING =====
    housekeepingTitle: "သန့်ရှင်းရေး",
    housekeepingSubtitle: "သန့်ရှင်းရေးနှင့် ပြုပြင်ရေး လုပ်ငန်းများကို စီမံပါ။",
    newTask: "လုပ်ငန်း အသစ်",
    priority: "ဦးစားပေး",
    assigned: "တာဝန်ပေး",
    created: "ဖန်တီးချိန်",
    cleaningType: "သန့်ရှင်းရေး",
    maintenanceType: "ပြုပြင်ရေး",
    inspection: "စစ်ဆေးရေး",
    low: "နိမ့်",
    normal: "ပုံမှန်",
    high: "မြင့်",
    urgent: "အရေးပေါ်",
    pending: "ဆိုင်းငံ့",
    inProgress: "လုပ်ဆောင်နေ",
    completed: "ပြီးစီး",
    cancelled: "ပယ်ဖျက်",
    notes: "မှတ်ချက်",
    createTaskBtn: "လုပ်ငန်း ဖန်တီးရန်",
    taskCreated: "လုပ်ငန်း ဖန်တီးပြီးပါပြီ",
    taskCompleted: "လုပ်ငန်း ပြီးစီးပါပြီ",
    unassigned: "တာဝန်မပေးရသေး",
    assignTo: "တာဝန်ပေးရန်",
    selectRoom: "အခန်း ရွေးပါ",

    // ===== USERS =====
    usersTitle: "အသုံးပြုသူ စီမံခန့်ခွဲမှု",
    usersSubtitle: "စနစ်အသုံးပြုသူများနှင့် အခန်းကဏ္ဍများကို စီမံပါ။",
    addUser: "အသုံးပြုသူ ထည့်ရန်",
    user: "အသုံးပြုသူ",
    role: "အခန်းကဏ္ဍ",
    name: "အမည်",
    editUser: "အသုံးပြုသူ ပြင်ဆင်ရန်",
    createUserBtn: "အသုံးပြုသူ ဖန်တီးရန်",
    resetPassword: "စကားဝှက် ပြန်လည်သတ်မှတ်ရန်",
    newPassword: "စကားဝှက် အသစ်",
    confirmPassword: "စကားဝှက် အတည်ပြုရန်",
    updatePassword: "စကားဝှက် ပြင်ဆင်ရန်",
    userCreated: "အသုံးပြုသူ ဖန်တီးပြီးပါပြီ",
    userUpdated: "အသုံးပြုသူ ပြင်ဆင်ပြီးပါပြီ",
    userDisabled: "အသုံးပြုသူ ပိတ်ပြီးပါပြီ",
    userEnabled: "အသုံးပြုသူ ဖွင့်ပြီးပါပြီ",
    passwordUpdated: "စကားဝှက် ပြင်ဆင်ပြီးပါပြီ",
    userSearchPlaceholder: "အသုံးပြုသူများ ရှာပါ...",
    minSixChars: "အနည်းဆုံး စာလုံး ၆ လုံး",
    admin: "အက်မင်",
    manager: "မန်နေဂျာ",
    reception: "ရီဆက်ရှင်",
    cleaner: "သန့်ရှင်းရေးဝန်ထမ်း",

    // ===== SETTINGS =====
    settingsTitle: "ဆက်တင်များ",
    settingsSubtitle: "ဟိုတယ် အချက်အလက်၊ ငွေကြေး၊ အချိန်ဇုန်နှင့် အရန်သိမ်းမှုကို ပြင်ဆင်ပါ။",
    hotelInfo: "ဟိုတယ် အချက်အလက်",
    hotelName: "ဟိုတယ် အမည်",
    contactEmail: "ဆက်သွယ်ရန် အီးမေးလ်",
    contactPhone: "ဆက်သွယ်ရန် ဖုန်း",
    address: "လိပ်စာ",
    regionalSettings: "ဒေသဆိုင်ရာ ဆက်တင်များ",
    language: "ဘာသာစကား",
    currency: "ငွေကြေး",
    currencySymbol: "ငွေကြေး သင်္ကေတ",
    timezone: "အချိန်ဇုန်",
    operations: "လုပ်ငန်းဆောင်တာများ",
    checkInTime: "Check In အချိန်",
    checkOutTime: "Check Out အချိန်",
    taxRate: "အခွန် နှုန်း %",
    overtimeGrace: "အချိန်ပို ခွင့်ပြုချိန် (မိနစ်)",
    invoiceFooter: "ဘောင်ချာ အောက်ခြေ",
    saveSettings: "ဆက်တင်များ သိမ်းရန်",
    saving: "သိမ်းနေသည်...",
    settingsSaved: "ဆက်တင်များ သိမ်းပြီးပါပြီ",
    english: "English",
    myanmar: "မြန်မာ",
    autoBrowser: "Auto (Browser)",

    // ===== REPORTS =====
    reportsTitle: "အစီရင်ခံစာများ",
    reportsSubtitle: "ဧည့်သည် အသေးစိတ်၊ ဝင်ငွေနှင့် ငွေပေးချေမှုများ ပါဝင်သော ဟိုတယ် အစီရင်ခံစာများ။",
    overview: "အနှစ်ချုပ်",
    guestList: "ဧည့်သည် စာရင်း",
    paymentsTab: "ငွေပေးချေမှုများ",
    revenue: "ဝင်ငွေ",
    unpaid: "မပေးချေရသေး",
    from: "မှ",
    to: "အထိ",
    apply: "အသုံးပြုရန်",
    today: "ယနေ့",
    thisMonth: "ဤလ",
    totalRevenueLabel: "စုစုပေါင်း ဝင်ငွေ",
    totalPayments: "စုစုပေါင်း ငွေပေးချေမှု",
    reservationsLabel: "ဘွတ်များ",
    occupancy: "အခန်းပြည့်နှုန်း",
    arrivals: "ဧည့်သည်ဝင်",
    departures: "ဧည့်သည်ထွက်",
    cancellations: "ပယ်ဖျက်မှုများ",
    totalUnpaid: "စုစုပေါင်း မပေးချေရသေး",
    revenueByDate: "ရက်စွဲအလိုက် ဝင်ငွေ",
    paymentsByMethod: "နည်းလမ်းအလိုက် ငွေပေးချေမှု",
    exportCsv: "CSV",
    exportAllGuests: "ဧည့်သည်အားလုံး Export",
    exportPayments: "ငွေပေးချေမှု Export",
    exportUnpaid: "မပေးချေရသေး Export",
    guestSearchPlaceholder: "အမည်၊ ဘွတ်၊ NRC၊ ပတ်စပို့၊ အခန်း ရှာပါ...",
    paymentMethods: "ငွေပေးချေ နည်းလမ်းများ",
    transactions: "ငွေလွှဲမှတ်တမ်းများ",
    additionalInfo: "ထပ်ဆောင်း အချက်အလက်",
    noPayments: "ငွေပေးချေမှု မရှိပါ",
    noTransactions: "ငွေလွှဲမှတ်တမ်း မရှိပါ",
    booked: "ဘွတ်ယူချိန်",
    totalAmount: "စုစုပေါင်း ပမာဏ",
    totalTransactions: "စုစုပေါင်း ငွေလွှဲ",
    outstandingBalance: "စုစုပေါင်း လက်ကျန်",
    allClear: "မပေးချေရသေးသည့် ဘွတ်မရှိပါ။ အားလုံး ကောင်းပါသည်!",
    receiptNo: "ဘောင်ချာ နံပါတ်",

    // ===== BACKUPS =====
    backupsTitle: "အရန်သိမ်းမှုနှင့် ပြန်လည်ရယူမှု",
    backupsSubtitle: "ဒေတာဘေ့စ် အရန်သိမ်းမှုများ ဖန်တီး၊ ဒေါင်းလုဒ်နှင့် ပြန်လည်ရယူပါ။",
    createBackupBtn: "အရန်သိမ်းမှု ဖန်တီးရန်",
    creating: "ဖန်တီးနေသည်...",
    restoreFromFile: "ဖိုင်မှ ပြန်လည်ရယူရန်",
    restoreWarning: "သတိ: ယခုလက်ရှိ ဒေတာအားလုံးကို အစားထိုးပါမည်။",
    iUnderstand: "နားလည်ပါသည်",
    restoreBtn: "ပြန်လည်ရယူရန်",
    restoring: "ပြန်လည်ရယူနေသည်...",
    filename: "ဖိုင်နာမည်",
    size: "အရွယ်အစား",
    download: "ဒေါင်းလုဒ်",
    backupCreated: "အရန်သိမ်းမှု ဖန်တီးပြီးပါပြီ",
    backupDeleted: "ဖျက်ပြီးပါပြီ",
    restoreCompleted: "ပြန်လည်ရယူမှု ပြီးစီးပါပြီ",
    chooseFile: "ဖိုင် ရွေးပါ",
    pleaseConfirm: "အတည်ပြုပါ",
    overwriteConfirm: "ယခုလက်ရှိ ဒေတာအားလုံးကို အစားထိုးပါမည်။ သေချာပါသလား?",

    // ===== AUDIT LOGS =====
    auditTitle: "စစ်ဆေးမှု မှတ်တမ်းများ",
    auditSubtitle: "စနစ် လုပ်ဆောင်ချက်များနှင့် ဒေတာ ပြောင်းလဲမှုများကို မှတ်တမ်းတင်ပါ။",
    time: "အချိန်",
    entity: "အရာဝတ္ထု",
    ip: "IP",
    before: "မပြင်ဆင်မီ",
    after: "ပြင်ဆင်ပြီး",
    device: "စက်",
    auditSearch: "ရှာရန်",
    allUsers: "အားလုံး",
    allEntities: "အားလုံး",
    noActivities: "လုပ်ဆောင်ချက် မတွေ့ပါ။",
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem("app_language") || "en"
  );

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem("app_language", newLanguage);
  };

  const t = (key) => {
    return (
      translations[language]?.[key] ||
      translations.en[key] ||
      key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);