import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // COMMON
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    refresh: "Refresh",
    close: "Close",
    actions: "Actions",
    status: "Status",
    yes: "Yes",
    no: "No",
    all: "All",
    back: "Back",
    confirm: "Confirm",
    warning: "Warning",
    error: "Error",
    success: "Success",
    noData: "No data found.",
    details: "Details",

    // LOGIN
    loginTitle: "Hotel Management System",
    loginSubtitle: "Sign in to your account",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidCredentials: "Invalid username or password",
    loginFooter: "Hotel Property Management System",

    // LAYOUT
    dashboard: "Dashboard",
    roomBoard: "Room Board",
    rooms: "Rooms",
    reservations: "Reservations",
    vouchers: "Vouchers",
    payments: "Payments",
    housekeeping: "Housekeeping",
    reports: "Reports",
    backups: "Backups",
    auditLogs: "Audit Logs",
    users: "Users",
    settings: "Settings",
    logout: "Logout",
    hotelManagement: "Hotel Management",

    // DASHBOARD
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Welcome back! Here is what's happening at your hotel today.",
    todayRevenue: "Today's Revenue",
    monthlyRevenue: "Monthly Revenue",
    arrivalsToday: "Today's Arrivals",
    departuresToday: "Today's Departures",
    occupancyRate: "Occupancy Rate",
    roomStatusOverview: "Room Status Overview",
    available: "Available",
    occupied: "Occupied",
    reserved: "Reserved",
    cleaning: "Cleaning",
    maintenance: "Maintenance",
    maint: "Maint.",
    blocked: "Blocked",
    quickActions: "Quick Actions",
    newReservation: "New Reservation",
    viewRoomBoard: "View Room Board",
    recordPayment: "Record Payment",
    todayArrivals: "Today's Arrivals",
    todayDepartures: "Today's Departures",
    recentPayments: "Recent Payments",
    needsAttention: "Needs Attention",
    noArrivals: "No arrivals today",
    noDepartures: "No departures today",
    noRecentPayments: "No recent payments",
    allRoomsOkay: "All rooms are in good condition",
    guests: "guests",
    of: "of",
    roomsText: "rooms",
    retry: "Retry",
    refreshing: "Refreshing...",
    cleaningTasks: "Cleaning Tasks",
    maintenanceTasks: "Maintenance Tasks",
    receiptNo: "Receipt No",

    // ROOMS
    roomsTitle: "Room Management",
    roomsSubtitle: "Manage your hotel rooms, pricing, and capacity.",
    addNewRoom: "Add New Room",
    roomSearchPlaceholder: "Search by room number or type...",
    room: "Room",
    type: "Type",
    capacity: "Capacity",
    floor: "Floor",
    pricePerNight: "Price / Night",
    editRoom: "Edit Room",
    roomNumber: "Room Number",
    roomType: "Room Type",
    maxGuests: "Max Guests (Capacity)",
    basePrice: "Base Price",
    extraBedPrice: "Extra Bed Price",
    overtimeRate: "Overtime Rate (per Hour)",
    createRoom: "Create Room",
    saveChanges: "Save Changes",
    roomCreated: "Room created successfully",
    roomUpdated: "Room updated successfully",
    roomDisabled: "Room disabled",
    disableRoomConfirm: "Are you sure you want to disable this room?",
    singleRoom: "1 Person (Single)",
    doubleRoom: "2 Persons (Double)",
    threePerson: "3 Persons",
    familyRoom: "4 Persons (Family)",
    fivePerson: "5 Persons",
    largeFamily: "6 Persons (Large Family)",
    groupRoom8: "8 Persons (Group)",
    groupRoom10: "10 Persons (Group)",
    standardRoom: "Standard",
    superiorRoom: "Superior",
    deluxeRoom: "Deluxe",
    premiumRoom: "Premium",
    executiveRoom: "Executive",
    familyRoomType: "Family Room",

    // ROOM BOARD
    roomBoardTitle: "Room Board",
    roomBoardSubtitle: "Visual overview of all room statuses by floor.",
    reserve: "Reserve",
    walkIn: "Walk-In",
    walkInShort: "Walk-In",
    pax: "PAX",
    night: "night",
    extendStay: "Extend Stay",
    confirmExtension: "Confirm Extension",
    extensionSuccess: "Stay extended successfully",
    addsAmount: "Adds",
    guestInformation: "Guest Information",
    timeLeft: "Time Left",
    noActiveReservation: "No active reservation for this room",
    viewInvoice: "View / Print Invoice",
    paymentsMade: "Payments Made",
    customDate: "Custom Date",
    invoice: "Invoice",

    // RESERVATIONS
    reservationsTitle: "Reservations",
    reservationsSubtitle: "Manage bookings, walk-ins, check-ins, and check-outs.",
    booking: "Booking",
    guest: "Guest",
    idLabel: "ID",
    checkIn: "Check In",
    checkOut: "Check Out",
    total: "Total",
    reservationSearchPlaceholder: "Search booking, guest, room, NRC, passport...",
    guestName: "Guest Name",
    guestPhone: "Guest Phone",
    guestType: "Guest Type",
    local: "Local (NRC)",
    foreigner: "Foreigner (Passport)",
    nrc: "NRC Number",
    passport: "Passport Number",
    nrcPlaceholder: "e.g. 12/YGN(N)123456",
    passportPlaceholder: "e.g. MA123456",
    adults: "Adults",
    children: "Children",
    extraBeds: "Extra Beds",
    voucherCode: "Voucher Code",
    enterCode: "Enter code",
    createReservationBtn: "Create Reservation",
    checkInWalkInGuest: "Check In Walk-In Guest",
    walkInMode: "Walk-In mode: The guest will be checked in immediately after creation.",
    walkInCheckInNote: "Walk-In: Check-in time is set to now",
    capacityLabel: "Capacity",
    guestsMax: "guests max",
    capacityWarning: "Warning: The total number of guests exceeds the room capacity. You cannot proceed.",
    reservationCreated: "Reservation created successfully",
    walkInSuccess: "Walk-In guest checked in successfully",
    checkedIn: "Checked In",
    checkedOut: "Checked Out",
    reservationCancelled: "Cancelled",
    walkInBadge: "WALK-IN",

    // VOUCHERS
    vouchersTitle: "Vouchers",
    vouchersSubtitle: "Manage discount codes.",
    newVoucher: "New Voucher",
    code: "Code",
    usage: "Usage",
    validTo: "Valid Until",
    active: "Active",
    disabled: "Disabled",
    fixedAmount: "Fixed Amount",
    percentage: "Percentage",
    value: "Value",
    maxDiscount: "Max Discount",
    usageLimit: "Usage Limit",
    validFrom: "Valid From",
    createVoucherBtn: "Create Voucher",
    voucherCreated: "Voucher created successfully",
    voucherDisabled: "Voucher disabled",
    voucherSearchPlaceholder: "Search by code...",

    // PAYMENTS
    paymentsTitle: "Payments",
    paymentsSubtitle: "Record payments and view balances.",
    balances: "Balances",
    paymentHistory: "Payment History",
    paid: "Paid",
    balance: "Balance",
    receipt: "Receipt",
    method: "Method",
    amount: "Amount",
    date: "Date",
    reference: "Reference",
    note: "Note",
    savePaymentBtn: "Save Payment",
    cash: "Cash",
    card: "Card",
    bankTransfer: "Bank Transfer",
    other: "Other",
    paymentRecorded: "Payment recorded successfully",
    paymentSearchPlaceholder: "Search...",
    paidInFull: "Paid in Full",

    // INVOICE
    hotelInvoice: "Hotel Invoice",
    invoiceDate: "Invoice Date",
    bookingNo: "Booking No.",
    phone: "Phone",
    charges: "Charges",
    roomCharge: "Room Charge",
    extraBed: "Extra Bed",
    overtime: "Overtime",
    voucherDiscount: "Voucher Discount",
    totalLabel: "Total",
    paymentsLabel: "Payments",
    summary: "Summary",
    paidLabel: "Paid",
    balanceLabel: "Balance",
    paidInFullLabel: "PAID IN FULL",
    balanceDue: "BALANCE DUE",
    print: "Print",
    backToPayments: "Back to Payments",

    // HOUSEKEEPING
    housekeepingTitle: "Housekeeping",
    housekeepingSubtitle: "Manage cleaning and maintenance tasks.",
    newTask: "New Task",
    priority: "Priority",
    assigned: "Assigned",
    created: "Created",
    cleaningType: "Cleaning",
    maintenanceType: "Maintenance",
    inspection: "Inspection",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    notes: "Notes",
    createTaskBtn: "Create Task",
    taskCreated: "Task created successfully",
    taskCompleted: "Task completed successfully",
    unassigned: "Unassigned",
    assignTo: "Assign To",
    selectRoom: "Select Room",
    start:  "Start",
    cancle: "Cancle",

    // USERS
    usersTitle: "User Management",
    usersSubtitle: "Manage system users and roles.",
    addUser: "Add User",
    user: "User",
    role: "Role",
    name: "Name",
    editUser: "Edit User",
    createUserBtn: "Create User",
    resetPassword: "Reset Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    updatePassword: "Update Password",
    userCreated: "User created successfully",
    userUpdated: "User updated successfully",
    userDisabled: "User disabled",
    userEnabled: "User enabled",
    passwordUpdated: "Password updated successfully",
    userSearchPlaceholder: "Search users...",
    minSixChars: "Minimum 6 characters",
    admin: "Admin",
    manager: "Manager",
    reception: "Reception",
    cleaner: "Cleaner",

    // SETTINGS
    settingsTitle: "Settings",
    settingsSubtitle: "Configure hotel information, currency, timezone, and backup settings.",
    hotelInfo: "Hotel Information",
    hotelName: "Hotel Name",
    contactEmail: "Contact Email",
    contactPhone: "Contact Phone",
    address: "Address",
    regionalSettings: "Regional Settings",
    language: "Language",
    currency: "Currency",
    currencySymbol: "Currency Symbol",
    timezone: "Timezone",
    operations: "Operations",
    checkInTime: "Check-In Time",
    checkOutTime: "Check-Out Time",
    taxRate: "Tax Rate (%)",
    overtimeGrace: "Overtime Grace (min)",
    invoiceFooter: "Invoice Footer",
    saveSettings: "Save Settings",
    saving: "Saving...",
    settingsSaved: "Settings saved successfully",
    english: "English",
    myanmar: "Myanmar",
    autoBrowser: "Auto (Browser)",
    hotelLogo: "Hotel Logo",
    uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo",
    logoHint: "PNG, JPG or WEBP • Max 2 MB • Transparent background recommended",
    logoUpdated: "Logo updated successfully",
    logoRemoved: "Logo removed",

    // REPORTS
    reportsTitle: "Reports & Analytics",
    reportsSubtitle: "Comprehensive hotel reports with guest details, revenue, and payment information.",
    overview: "Overview",
    guestList: "Guest List",
    paymentsTab: "Payments",
    revenue: "Revenue",
    unpaid: "Unpaid",
    from: "From",
    to: "To",
    apply: "Apply",
    today: "Today",
    thisMonth: "This Month",
    totalRevenueLabel: "Total Revenue",
    totalPayments: "Total Payments",
    reservationsLabel: "Reservations",
    occupancy: "Occupancy",
    arrivals: "Arrivals",
    departures: "Departures",
    cancellations: "Cancellations",
    totalUnpaid: "Total Unpaid",
    revenueByDate: "Revenue By Date",
    paymentsByMethod: "Payments By Method",
    exportCsv: "CSV",
    exportAllGuests: "Export All Guests",
    exportPayments: "Export Payments",
    exportUnpaid: "Export Unpaid",
    guestSearchPlaceholder: "Search by name, booking, NRC, passport, or room...",
    paymentMethods: "Payment Methods",
    transactions: "Transactions",
    additionalInfo: "Additional Information",
    noPayments: "No payments",
    noTransactions: "No transactions",
    booked: "Booked",
    totalAmount: "Total Amount",
    totalTransactions: "Total Transactions",
    outstandingBalance: "Total Outstanding Balance",
    allClear: "No unpaid reservations. All clear!",

    // BACKUPS
    backupsTitle: "Backup & Restore",
    backupsSubtitle: "Create, download, and restore database backups.",
    createBackupBtn: "Create Backup",
    creating: "Creating...",
    restoreFromFile: "Restore From File",
    restoreWarning: "Warning: This will overwrite all current data.",
    iUnderstand: "I understand",
    restoreBtn: "Restore",
    restoring: "Restoring...",
    filename: "Filename",
    size: "Size",
    download: "Download",
    backupCreated: "Backup created successfully",
    backupDeleted: "Backup deleted",
    restoreCompleted: "Restore completed successfully",
    chooseFile: "Choose a File",
    pleaseConfirm: "Please confirm",
    overwriteConfirm:  "This will overwrite all current data. Are you sure?",

    // AUDIT LOGS
    auditTitle: "Audit Logs",
    auditSubtitle: "Track all system activities and data changes.",
    time: "Time",
    entity: "Entity",
    ip: "IP",
    before: "Before",
    after: "After",
    device: "Device",
    auditSearch: "Search",
    allUsers: "All",
    allEntities: "All",
    noActivities: "No activities found.",
    field: "Field",
    changes: "Changes",
    fieldsChanged: "field(s) changed",
    newRecordCreated: "New record created",
    recordDeleted: "Record deleted",
    noVisibleChanges: "No visible field changes (system metadata only)",
    viewRaw: "View Raw Data",
    hideRaw: "Hide Raw Data",
    none: "None",
    amenities: "Amenities",
    extraPersonPrice: "Extra Person Price",
    source: "Source",
    actualCheckIn: "Actual Check-In",
    actualCheckOut: "Actual Check-Out",
    taxAmount: "Tax Amount",

    //Notification
    notif_checkout_soon_title: "Check-out Reminder",
    notif_checkout_soon_msg: "Room {room} — {guest} checks out at {time} (in {mins} min)",
    notif_checkout_overtime_title: "OVERTIME Alert",
    notif_checkout_overtime_msg: "Room {room} — {guest} is {mins} min past check-out. Overtime charges applying.",
    notif_backup_overdue_title: "Backup Overdue",
    notif_backup_overdue_msg: "Last successful backup: {time}. Create or download a backup now.",
    notif_backup_failed_title: "Backup Failed",
    notif_backup_failed_msg: "Last backup attempt failed at {time}. Please check backups.",
    notif_digest_revenue_title: "Today's Revenue",
    notif_digest_revenue_msg: "Revenue so far {amount} • Arrivals {arrivals} • Departures {departures}",
    notif_digest_ops_title: "Today's Schedule",
    notif_digest_ops_msg: "Arrivals {arrivals} • Departures {departures}",
    mute: "Mute",
    unmute: "Unmute",
    solved: "Solved",
    soundOn: "Sound: On",
    soundOff: "Sound: Off",
    needsAction: "Needs Action",
    solvedCaption: "Solved · clears in 3 min",
    markAllRead: 'Make all read'
  },

  my: {
    // COMMON
    loading: "လုပ်ဆောင်နေသည်...",
    save: "သိမ်းရန်",
    cancel: "ပယ်ဖျက်ရန်",
    create: "ဖန်တီးရန်",
    edit: "ပြင်ဆင်ရန်",
    delete: "ဖျက်ရန်",
    search: "ရှာဖွေရန်",
    refresh: "ပြန်လည်တင်ရန်",
    close: "ပိတ်ရန်",
    actions: "လုပ်ဆောင်ချက်များ",
    status: "အခြေအနေ",
    yes: "ဟုတ်ကဲ့",
    no: "မဟုတ်ပါ",
    all: "အားလုံး",
    back: "နောက်သို့",
    confirm: "အတည်ပြုရန်",
    warning: "သတိပေးချက်",
    error: "အမှား",
    success: "အောင်မြင်ပါသည်",
    noData: "ဒေတာ မတွေ့ပါ။",
    details: "အသေးစိတ်",

    // LOGIN
    loginTitle: "ဟိုတယ် စီမံခန့်ခွဲမှုစနစ်",
    loginSubtitle: "သင့်အကောင့်သို့ ဝင်ရောက်ပါ",
    username: "အသုံးပြုသူအမည်",
    password: "စကားဝှက်",
    signIn: "ဝင်ရောက်ရန်",
    signingIn: "ဝင်ရောက်နေသည်...",
    invalidCredentials: "အသုံးပြုသူအမည် သို့မဟုတ် စကားဝှက် မှားယွင်းနေပါသည်",
    loginFooter: "ဟိုတယ် စီမံခန့်ခွဲမှုစနစ်",

    // LAYOUT
    dashboard: "အနှစ်ချုပ်",
    roomBoard: "အခန်းအခြေအနေ",
    rooms: "အခန်းများ",
    reservations: "ကြိုတင်မှာယူမှုများ",
    vouchers: "ဘောက်ချာများ",
    payments: "ငွေပေးချေမှုများ",
    housekeeping: "အခန်းသန့်ရှင်းရေး",
    reports: "အစီရင်ခံစာများ",
    backups: "အရန်သိမ်းဆည်းမှုများ",
    auditLogs: "စစ်ဆေးမှုမှတ်တမ်းများ",
    users: "အသုံးပြုသူများ",
    settings: "ဆက်တင်များ",
    logout: "ထွက်ရန်",
    hotelManagement: "ဟိုတယ် စီမံခန့်ခွဲမှု",

    // DASHBOARD
    dashboardTitle: "အနှစ်ချုပ်",
    dashboardSubtitle:"ပြန်လည်ကြိုဆိုပါတယ်။ ယနေ့ ဟိုတယ်၏ လုပ်ငန်းအခြေအနေများကို ဤနေရာတွင် ကြည့်ရှုနိုင်ပါသည်။",
    todayRevenue: "ယနေ့ ဝင်ငွေ",
    monthlyRevenue: "လစဉ် ဝင်ငွေ",
    arrivalsToday: "ယနေ့ ဧည့်သည်ဝင်ရောက်မှု",
    departuresToday: "ယနေ့ ဧည့်သည်ထွက်ခွာမှု",
    occupancyRate: "အခန်းပြည့်နှုန်း",
    roomStatusOverview: "အခန်းအခြေအနေ အနှစ်ချုပ်",
    available: "လွတ်နေသည်",
    occupied: "အသုံးပြုနေသည်",
    reserved: "ကြိုတင်မှာယူထားသည်",
    cleaning: "သန့်ရှင်းရေး",
    maintenance: "ပြုပြင်ရေး",
    maint: "ပြုပြင်",
    blocked: "ပိတ်ထားသည်",
    quickActions: "အမြန်လုပ်ဆောင်ချက်များ",
    newReservation: "ကြိုတင်မှာယူမှုအသစ်",
    viewRoomBoard: "အခန်းဘုတ် ကြည့်ရန်",
    recordPayment: "ငွေပေးချေမှု မှတ်တမ်းတင်ရန်",
    todayArrivals: "ယနေ့ ဧည့်သည်ဝင်ရောက်မှု",
    todayDepartures: "ယနေ့ ဧည့်သည်ထွက်ခွာမှု",
    recentPayments: "လတ်တလော ငွေပေးချေမှုများ",
    needsAttention: "အာရုံစိုက်ရန်",
    noArrivals: "ယနေ့ ဧည့်သည်ဝင်ရောက်မှု မရှိပါ",
    noDepartures: "ယနေ့ ဧည့်သည်ထွက်ခွာမှု မရှိပါ",
    noRecentPayments: "လတ်တလော ငွေပေးချေမှု မရှိပါ",
    allRoomsOkay: "အခန်းအားလုံး အဆင်ပြေပါသည်",
    guests: "ဧည့်သည်",
    of: "/",
    roomsText: "အခန်း",
    retry: "ထပ်ကြိုးစားရန်",
    refreshing: "အသစ်ပြန်လုပ်နေသည်...",
    cleaningTasks: "သန့်ရှင်းရေး လုပ်ငန်းများ",
    maintenanceTasks: "ပြုပြင်ရေး လုပ်ငန်းများ",

    // ROOMS
    roomsTitle: "အခန်း စီမံခန့်ခွဲမှု",
    roomsSubtitle: "ဟိုတယ်အခန်းများ၊ စျေးနှုန်းများနှင့် ဧည့်သည်လက်ခံနိုင်သည့် အရေအတွက်ကို စီမံပါ။",
    addNewRoom: "အခန်းအသစ် ထည့်ရန်",
    roomSearchPlaceholder: "အခန်းနံပါတ် သို့မဟုတ် အမျိုးအစားဖြင့် ရှာဖွေပါ...",
    room: "အခန်း",
    type: "အမျိုးအစား",
    capacity: "ဧည့်သည်လက်ခံနိုင်မှု",
    floor: "ထပ်",
    pricePerNight: "တစ်ည စျေးနှုန်း",
    editRoom: "အခန်း ပြင်ဆင်ရန်",
    roomNumber: "အခန်းနံပါတ်",
    roomType: "အခန်းအမျိုးအစား",
    maxGuests: "ဧည့်သည်အများဆုံး လက်ခံနိုင်သည့်အရေအတွက်",
    basePrice: "အခြေခံစျေးနှုန်း",
    extraBedPrice: "အပိုကုတင် စျေးနှုန်း",
    overtimeRate: "အချိန်ပို စျေးနှုန်း (တစ်နာရီ)",
    createRoom: "အခန်း ဖန်တီးရန်",
    saveChanges: "ပြောင်းလဲမှုများ သိမ်းရန်",
    roomCreated: "အခန်းကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ",
    roomUpdated: "အခန်းကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ",
    roomDisabled: "အခန်းကို ပိတ်ထားပြီးပါပြီ",
    disableRoomConfirm: "ဤအခန်းကို ပိတ်ထားရန် သေချာပါသလား?",
    singleRoom: "၁ ယောက် (Single)",
    doubleRoom: "၂ ယောက် (Double)",
    threePerson: "၃ ယောက်",
    familyRoom: "၄ ယောက် (Family)",
    fivePerson: "၅ ယောက်",
    largeFamily: "၆ ယောက် (Large Family)",
    groupRoom8: "၈ ယောက် (Group)",
    groupRoom10: "၁၀ ယောက် (Group)",
    standardRoom: "Standard",
    superiorRoom: "Superior",
    deluxeRoom: "Deluxe",
    premiumRoom: "Premium",
    executiveRoom: "Executive",
    familyRoomType: "Family Room",

    // ROOM BOARD
    roomBoardTitle: "အခန်းအခြေအနေ",
    roomBoardSubtitle: "ထပ်အလိုက် အခန်းအခြေအနေများကို တစ်နေရာတည်းတွင် ကြည့်ရှုနိုင်ပါသည်။",
    reserve: "ကြိုတင်မှာယူရန်",
    walkIn: "Walk-In",
    walkInShort: "Walk-In",
    pax: "ဧည့်သည်ဦးရေ",
    night: "ည",
    extendStay: "နေထိုင်မှု သက်တမ်းတိုးရန်",
    confirmExtension: "သက်တမ်းတိုး အတည်ပြုရန်",
    extensionSuccess: "နေထိုင်မှု သက်တမ်းတိုးပြီးပါပြီ",
    addsAmount: "ထပ်တိုးငွေ",
    guestInformation: "ဧည့်သည် အချက်အလက်",
    timeLeft: "ကျန်ချိန်",
    noActiveReservation: "ဤအခန်းအတွက် လက်ရှိ ဘွတ်ကင်း မရှိပါ",
    viewInvoice: "ဘောင်ချာ ကြည့်/ပရင့်ရန်",
    paymentsMade: "ပေးချေပြီးမှုများ",
    customDate: "ရက်စွဲ ရွေးရန်",
    invoice: "ဘောင်ချာ",

    // RESERVATIONS
    reservationsTitle: "ကြိုတင်မှာယူမှုများ",
    reservationsSubtitle:  "ကြိုတင်မှာယူမှုများ၊ Walk-In ဧည့်သည်များ၊ Check-In နှင့် Check-Out များကို စီမံပါ။",
    booking: "ဘွတ်ကင်",
    guest: "ဧည့်သည်",
    idLabel: "ID",
    checkIn: "Check In",
    checkOut: "Check Out",
    total: "စုစုပေါင်း",
    reservationSearchPlaceholder: "ဘွတ်ကင်၊ ဧည့်သည်၊ အခန်း၊ NRC သို့မဟုတ် ပတ်စပို့ဖြင့် ရှာဖွေပါ...",
    guestName: "ဧည့်သည်အမည်",
    guestPhone: "ဧည့်သည်ဖုန်း",
    guestType: "ဧည့်သည်အမျိုးအစား",
    local: "ပြည်တွင်း (NRC)",
    foreigner: "နိုင်ငံခြားသား (Passport)",
    nrc: "NRC နံပါတ်",
    passport: "Passport နံပါတ်",
    nrcPlaceholder: "ဥပမာ 12/ရကန(နိုင်)123456",
    passportPlaceholder: "ဥပမာ MA123456",
    adults: "လူကြီး",
    children: "ကလေး",
    extraBeds: "အပိုကုတင်",
    voucherCode: "ဘောက်ချာကုဒ်",
    enterCode: "ကုဒ် ထည့်ပါ",
    createReservationBtn: "ကြိုတင်မှာယူမှု ပြုလုပ်ရန်",
    checkInWalkInGuest: "Walk-In ဧည့်သည်ကို Check In ပြုလုပ်ရန်",
    walkInMode:  "Walk-In မုဒ်: ဧည့်သည်စာရင်းဖန်တီးပြီးသည်နှင့် ချက်ချင်း Check In ပြုလုပ်ပါမည်။",
    walkInCheckInNote: "Walk-In: Check In အချိန်ကို ယခုအချိန်အဖြစ် သတ်မှတ်ထားပါသည်။",
    capacityLabel: "ဧည့်သည်လက်ခံနိုင်မှု",
    guestsMax: "ဧည့်သည် အများဆုံး",
    capacityWarning: "သတိပေးချက်: ဧည့်သည်စုစုပေါင်းအရေအတွက်သည် အခန်း၏ လက်ခံနိုင်သည့်အရေအတွက်ထက် ကျော်လွန်နေပါသည်။ ဆက်လက်လုပ်ဆောင်၍ မရပါ။",
    reservationCreated: "ကြိုတင်မှာယူမှုကို အောင်မြင်စွာ ပြုလုပ်ပြီးပါပြီ",
    walkInSuccess: "Walk-In ဧည့်သည်ကို အောင်မြင်စွာ Check In ပြုလုပ်ပြီးပါပြီ",
    checkedIn: "Check In ပြုလုပ်ပြီး",
    checkedOut: "Check Out ပြုလုပ်ပြီး",
    reservationCancelled: "ပယ်ဖျက်ပြီး",
    walkInBadge: "WALK-IN",

    // VOUCHERS
    vouchersTitle: "ဘောက်ချာများ",
    vouchersSubtitle: "လျှော့စျေးကုဒ်များကို စီမံပါ။",
    newVoucher: "ဘောက်ချာအသစ်",
    code: "ကုဒ်",
    usage: "အသုံးပြုမှု",
    validTo: "သက်တမ်းကုန်ဆုံးမည့်ရက်",
    active: "အသက်ဝင်",
    disabled: "ပိတ်ထား",
    fixedAmount: "သတ်မှတ်ငွေပမာဏ",
    percentage: "ရာခိုင်နှုန်း",
    value: "တန်ဖိုး",
    maxDiscount: "အများဆုံး လျှော့စျေး",
    usageLimit: "အသုံးပြုနိုင်သည့် အကြိမ်ရေ",
    validFrom: "စတင်အသုံးပြုနိုင်သည့်ရက်",
    createVoucherBtn: "ဘောက်ချာ ဖန်တီးရန်",
    voucherCreated: "ဘောက်ချာကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ",
    voucherDisabled: "ဘောက်ချာကို ပိတ်ထားပြီးပါပြီ",
    voucherSearchPlaceholder: "ကုဒ်ဖြင့် ရှာဖွေပါ...",

    // PAYMENTS
    paymentsTitle: "ငွေပေးချေမှုများ",
    paymentsSubtitle: "ငွေပေးချေမှုများကို မှတ်တမ်းတင်ပြီး လက်ကျန်ငွေများကို ကြည့်ရှုပါ။",
    balances: "လက်ကျန်များ",
    paymentHistory: "ငွေပေးချေမှု မှတ်တမ်း",
    paid: "ပေးချေပြီး",
    balance: "လက်ကျန်",
    receipt: "ပြေစာ",
    method: "နည်းလမ်း",
    amount: "ပမာဏ",
    date: "ရက်စွဲ",
    reference: "ရည်ညွှန်းနံပါတ်",
    note: "မှတ်ချက်",
    savePaymentBtn: "ငွေပေးချေမှု သိမ်းရန်",
    cash: "ငွေသား",
    card: "ကတ်",
    bankTransfer: "ဘဏ်လွှဲ",
    other: "အခြား",
    paymentRecorded: "ငွေပေးချေမှုကို အောင်မြင်စွာ မှတ်တမ်းတင်ပြီးပါပြီ",
    paymentSearchPlaceholder: "ရှာဖွေပါ...",
    paidInFull: "အပြည့်အဝ ပေးချေပြီး",

    // INVOICE
    hotelInvoice: "ဟိုတယ် ငွေတောင်းခံလွှာ",
    invoiceDate: "ငွေတောင်းခံလွှာ ရက်စွဲ",
    bookingNo: "ဘွတ်ကင်နံပါတ်",
    phone: "ဖုန်း",
    charges: "ကျသင့်ငွေများ",
    roomCharge: "အခန်းခ",
    extraBed: "အပိုကုတင်",
    overtime: "အချိန်ပို",
    voucherDiscount: "ဘောက်ချာ လျှော့စျေး",
    totalLabel: "စုစုပေါင်း",
    paymentsLabel: "ငွေပေးချေမှုများ",
    summary: "အနှစ်ချုပ်",
    paidLabel: "ပေးချေပြီး",
    balanceLabel: "လက်ကျန်",
    paidInFullLabel: "အပြည့်အဝ ပေးချေပြီး",
    balanceDue: "ပေးရန်လက်ကျန်",
    print: "ပရင့်ထုတ်ရန်",
    backToPayments: "ငွေပေးချေမှုများသို့ ပြန်သွားရန်",

    // HOUSEKEEPING
    housekeepingTitle: "အခန်းသန့်ရှင်းရေး",
    housekeepingSubtitle: "သန့်ရှင်းရေးနှင့် ပြုပြင်ရေး လုပ်ငန်းများကို စီမံပါ။",
    newTask: "လုပ်ငန်းအသစ်",
    priority: "ဦးစားပေး",
    assigned: "တာဝန်ပေးထားသူ",
    created: "ဖန်တီးသည့်အချိန်",
    cleaningType: "သန့်ရှင်းရေး",
    maintenanceType: "ပြုပြင်ရေး",
    inspection: "စစ်ဆေးရေး",
    low: "နိမ့်",
    normal: "ပုံမှန်",
    high: "မြင့်",
    urgent: "အရေးပေါ်",
    pending: "စောင့်ဆိုင်းနေသည်",
    inProgress: "လုပ်ဆောင်နေသည်",
    completed: "ပြီးစီးပြီ",
    cancelled: "ပယ်ဖျက်ပြီး",
    notes: "မှတ်ချက်",
    createTaskBtn: "လုပ်ငန်း ဖန်တီးရန်",
    taskCreated: "လုပ်ငန်းကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ",
    taskCompleted: "လုပ်ငန်း ပြီးစီးပါပြီ",
    unassigned: "တာဝန်မပေးရသေး",
    assignTo: "တာဝန်ပေးရန်",
    selectRoom: "အခန်း ရွေးချယ်ပါ",
    start:  "စတင်မည်",
    cancle: "ပယ်ဖျက်မည်",
    

    // USERS
    usersTitle: "အသုံးပြုသူ စီမံခန့်ခွဲမှု",
    usersSubtitle:  "စနစ်အသုံးပြုသူများနှင့် အခန်းကဏ္ဍများကို စီမံပါ။",
    addUser: "အသုံးပြုသူ ထည့်ရန်",
    user: "အသုံးပြုသူ",
    role: "အခန်းကဏ္ဍ",
    name: "အမည်",
    editUser: "အသုံးပြုသူ ပြင်ဆင်ရန်",
    createUserBtn: "အသုံးပြုသူ ဖန်တီးရန်",
    resetPassword: "စကားဝှက် ပြန်လည်သတ်မှတ်ရန်",
    newPassword: "စကားဝှက်အသစ်",
    confirmPassword: "စကားဝှက် အတည်ပြုရန်",
    updatePassword: "စကားဝှက် ပြင်ဆင်ရန်",
    userCreated: "အသုံးပြုသူကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ",
    userUpdated: "အသုံးပြုသူကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ",
    userDisabled: "အသုံးပြုသူကို ပိတ်ထားပြီးပါပြီ",
    userEnabled: "အသုံးပြုသူကို ဖွင့်ထားပြီးပါပြီ",
    passwordUpdated: "စကားဝှက်ကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ",
    userSearchPlaceholder: "အသုံးပြုသူများကို ရှာဖွေပါ...",
    minSixChars: "အနည်းဆုံး စာလုံး ၆ လုံး",
    admin: "အက်မင်",
    manager: "မန်နေဂျာ",
    reception: "ဧည့်ကြိုဝန်ထမ်း",
    cleaner: "သန့်ရှင်းရေးဝန်ထမ်း",

    // SETTINGS
    settingsTitle: "ဆက်တင်များ",
    settingsSubtitle: "ဟိုတယ်အချက်အလက်၊ ငွေကြေး၊ အချိန်ဇုန်နှင့် အရန်သိမ်းမှုဆိုင်ရာ ဆက်တင်များကို ပြင်ဆင်ပါ။",
    hotelInfo: "ဟိုတယ် အချက်အလက်",
    hotelName: "ဟိုတယ်အမည်",
    contactEmail: "ဆက်သွယ်ရန် အီးမေးလ်",
    contactPhone: "ဆက်သွယ်ရန် ဖုန်း",
    address: "လိပ်စာ",
    regionalSettings: "ဒေသဆိုင်ရာ ဆက်တင်များ",
    language: "ဘာသာစကား",
    currency: "ငွေကြေး",
    currencySymbol: "ငွေကြေး သင်္ကေတ",
    timezone: "အချိန်ဇုန်",
    operations: "လုပ်ငန်းဆောင်တာများ",
    checkInTime: "Check In အချိန်",
    checkOutTime: "Check Out အချိန်",
    taxRate: "အခွန်နှုန်းထား (%)",
    overtimeGrace: "အချိန်ပို ခွင့်ပြုချိန် (မိနစ်)",
    invoiceFooter: "ငွေတောင်းခံလွှာ အောက်ခြေစာသား",
    saveSettings: "ဆက်တင်များ သိမ်းရန်",
    saving: "သိမ်းဆည်းနေသည်...",
    settingsSaved: "ဆက်တင်များကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ",
    english: "English",
    myanmar: "မြန်မာ",
    autoBrowser: "အလိုအလျောက် (Browser)",
    hotelLogo: "ဟိုတယ် လိုဂို",
    uploadLogo: "လိုဂို တင်ရန်",
    removeLogo: "လိုဂို ဖယ်ရှားရန်",
    logoHint: "PNG, JPG သို့မဟုတ် WEBP • အများဆုံး 2 MB • နောက်ခံအလွတ် ထားရန် အကြံပြုသည်",
    logoUpdated: "လိုဂို အသစ်ပြင်ဆင်ပြီးပါပြီ",
    logoRemoved: "လိုဂို ဖယ်ရှားပြီးပါပြီ",

    // REPORTS
    reportsTitle: "အစီရင်ခံစာများနှင့် ခွဲခြမ်းစိတ်ဖြာမှု",
    reportsSubtitle:  "ဧည့်သည်အချက်အလက်၊ ဝင်ငွေနှင့် ငွေပေးချေမှုများ ပါဝင်သော ဟိုတယ်အစီရင်ခံစာများကို ကြည့်ရှုနိုင်ပါသည်။",
    overview: "အနှစ်ချုပ်",
    guestList: "ဧည့်သည်စာရင်း",
    paymentsTab: "ငွေပေးချေမှုများ",
    revenue: "ဝင်ငွေ",
    unpaid: "မပေးချေရသေး",
    from: "မှ",
    to: "အထိ",
    apply: "အသုံးပြုရန်",
    today: "ယနေ့",
    thisMonth: "ဤလ",
    totalRevenueLabel: "စုစုပေါင်း ဝင်ငွေ",
    totalPayments: "စုစုပေါင်း ငွေပေးချေမှု",
    reservationsLabel: "ကြိုတင်မှာယူမှုများ",
    occupancy: "အခန်းပြည့်နှုန်း",
    arrivals: "ဧည့်သည်ဝင်ရောက်မှု",
    departures: "ဧည့်သည်ထွက်ခွာမှု",
    cancellations: "ပယ်ဖျက်မှုများ",
    totalUnpaid: "စုစုပေါင်း မပေးချေရသေးသောငွေ",
    revenueByDate: "ရက်စွဲအလိုက် ဝင်ငွေ",
    paymentsByMethod: "ငွေပေးချေမှုနည်းလမ်းအလိုက်",
    exportCsv: "CSV",
    exportAllGuests: "ဧည့်သည်အားလုံးကို Export ပြုလုပ်ရန်",
    exportPayments: "ငွေပေးချေမှုများကို Export ပြုလုပ်ရန်",
    exportUnpaid: "မပေးချေရသေးသောငွေများကို Export ပြုလုပ်ရန်",
    guestSearchPlaceholder: "အမည်၊ ဘွတ်ကင်၊ NRC၊ ပတ်စပို့ သို့မဟုတ် အခန်းဖြင့် ရှာဖွေပါ...",
    paymentMethods: "ငွေပေးချေမှု နည်းလမ်းများ",
    transactions: "ငွေပေးချေမှု မှတ်တမ်းများ",
    additionalInfo: "ထပ်ဆောင်း အချက်အလက်",
    noPayments: "ငွေပေးချေမှု မရှိပါ",
    noTransactions: "ငွေပေးချေမှု မှတ်တမ်း မရှိပါ",
    booked: "ကြိုတင်မှာယူထားသည်",
    totalAmount: "စုစုပေါင်း ပမာဏ",
    totalTransactions: "စုစုပေါင်း ငွေပေးချေမှုမှတ်တမ်း",
    outstandingBalance: "စုစုပေါင်း ပေးရန်လက်ကျန်",
    allClear: "မပေးချေရသေးသော ကြိုတင်မှာယူမှု မရှိပါ။ အားလုံး ရှင်းလင်းပါသည်။",
    receiptNo: "ပြေစာနံပါတ်",

    // BACKUPS
    backupsTitle: "အရန်သိမ်းဆည်းခြင်းနှင့် ပြန်လည်ရယူခြင်း",
    backupsSubtitle: "ဒေတာဘေ့စ် အရန်သိမ်းဆည်းမှုများကို ဖန်တီး၊ ဒေါင်းလုဒ်နှင့် ပြန်လည်ရယူပါ။",
    createBackupBtn: "အရန်သိမ်းဆည်းမှု ဖန်တီးရန်",
    creating: "ဖန်တီးနေသည်...",
    restoreFromFile: "ဖိုင်မှ ပြန်လည်ရယူရန်",
    restoreWarning: "သတိပေးချက်: ယခုလက်ရှိ ဒေတာအားလုံးကို အစားထိုးပါမည်။",
    iUnderstand: "နားလည်ပါသည်",
    restoreBtn: "ပြန်လည်ရယူရန်",
    restoring: "ပြန်လည်ရယူနေသည်...",
    filename: "ဖိုင်အမည်",
    size: "အရွယ်အစား",
    download: "ဒေါင်းလုဒ်",
    backupCreated: "အရန်သိမ်းဆည်းမှုကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ",
    backupDeleted: "အရန်သိမ်းဆည်းမှုကို ဖျက်ပြီးပါပြီ",
    restoreCompleted:"ဒေတာ ပြန်လည်ရယူခြင်း အောင်မြင်စွာ ပြီးစီးပါပြီ",
    chooseFile: "ဖိုင် ရွေးချယ်ရန်",
    pleaseConfirm: "အတည်ပြုပေးပါ",
    overwriteConfirm: "ယခုလက်ရှိ ဒေတာအားလုံးကို အစားထိုးပါမည်။ သေချာပါသလား?",

    // AUDIT LOGS
    auditTitle: "စစ်ဆေးမှု မှတ်တမ်းများ",
    auditSubtitle: "စနစ်အတွင်း လုပ်ဆောင်ချက်များနှင့် ဒေတာပြောင်းလဲမှုများကို မှတ်တမ်းတင်ထားပါသည်။",
    time: "အချိန်",
    entity: "ဒေတာအမျိုးအစား",
    ip: "IP",
    before: "မပြောင်းလဲမီ",
    after: "ပြောင်းလဲပြီးနောက်",
    device: "အသုံးပြုသည့်စက်",
    auditSearch: "ရှာဖွေရန်",
    allUsers: "အားလုံး",
    allEntities: "အားလုံး",
    noActivities: "လုပ်ဆောင်ချက်များ မတွေ့ပါ။",
    field: "အချက်",
    changes: "ပြောင်းလဲမှုများ",
    fieldsChanged: "ခု ပြောင်းလဲပြီး",
    newRecordCreated: "မှတ်တမ်းအသစ် ဖန်တီးပြီး",
    recordDeleted: "မှတ်တမ်း ဖျက်ပြီး",
    noVisibleChanges: "မြင်နိုင်သော ပြောင်းလဲမှု မရှိပါ (စနစ် metadata သာ)",
    viewRaw: "မူရင်းဒေတာ ကြည့်ရန်",
    hideRaw: "မူရင်းဒေတာ ဖျောက်ရန်",
    none: "မရှိပါ",
    amenities: "ဝန်ဆောင်မှု ပစ္စည်းများ",
    extraPersonPrice: "အပိုဧည့်သည် စျေးနှုန်း",
    source: "ရင်းမြစ်",
    actualCheckIn: "အမှန်တကယ် Check In",
    actualCheckOut: "အမှန်တကယ် Check Out",
    taxAmount: "အခွန် ပမာဏ",

    //Notification
    notif_checkout_soon_title: "Check-out သတိပေးချက်",
    notif_checkout_soon_msg: "အခန်း {room} — {guest} ကို {time} တွင် check-out လုပ်ရမည် ({mins} မိနစ်အတွင်း)",
    notif_checkout_overtime_title: "အချိန်ပို သတိပေးချက်",
    notif_checkout_overtime_msg: "အခန်း {room} — {guest} သည် check-out ထက် {mins} မိနစ် လွန်နေပါပြီ။ အချိန်ပိုကြေး ကျသင့်နေပါသည်။",
    notif_backup_overdue_title: "အရန်သိမ်းဆည်းမှု နောက်ကျနေပါသည်",
    notif_backup_overdue_msg: "နောက်ဆုံးအောင်မြင်သော အရန်သိမ်းဆည်းမှု: {time}။ ယခုပင် အရန်သိမ်းဆွဲပါ။",
    notif_backup_failed_title: "အရန်သိမ်း မအောင်မြင်ပါ",
    notif_backup_failed_msg: "နောက်ဆုံးအရန်သိမ်းဆည်းရန်ကြိုးစားမှု {time} တွင် မအောင်မြင်ပါ။ စစ်ဆေးပါ။",
    notif_digest_revenue_title: "ယနေ့ ဝင်ငွေ",
    notif_digest_revenue_msg: "လက်ရှိဝင်ငွေ {amount} • ဝင်ရောက် {arrivals} • ထွက်ခွာ {departures}",
    notif_digest_ops_title: "ယနေ့ အစီအစဉ်",
    notif_digest_ops_msg: "ဝင်ရောက် {arrivals} • ထွက်ခွာ {departures}",
    mute: "အသံပိတ်",
    unmute: "အသံဖွင့်",
    solved: "ဖြေရှင်းပြီး",
    soundOn: "အသံ: ဖွင့်",
    soundOff: "အသံ: ပိတ်",
    needsAction: "လုပ်ဆောင်ရန်",
    solvedCaption: "ဖြေရှင်းပြီး · ၃ မိနစ်အတွင်း ပျောက်မည်",
    markAllRead: 'အားလုံးဖတ်ပြီးသားလုပ်မည်'
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem("app_language") || "en"
  );

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem("app_language", newLanguage);
  };

  const t = (key) => {
    return (
      translations[language]?.[key] ||
      translations.en[key] ||
      key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);